### ISSUE TITLE
API: Position history

### ISSUE THREAD

**Issue by tomt1664** [commerceblock/mainstay-mvc#209]
The documentation shows the position query: https://testnet.mainstay.xyz/api/v1/position?position=1 returning merkle_roots and ops, the mainnet mainstay only returns a list of commitments. 

If the attestation TxID can also be added to each commitment object, then this would reduce the number of calls required when retrieving proof sequences.

**Comment by nkostoulas** [comment]
Must have been a mistake slimming down what the call returns because these info are not displayed in https://mainstay.xyz/position/1. Do you think it would be good to show any of this information in the website too?


We should split this position call to two; one for api and one for controller. The api one would show all this additional information. There is also a limit returning the last 10 entries. There is batching implemented but it is not that obvious. Maybe we should make it clearer in the docs.

**Comment by tomt1664** [comment]
I don't think it is necessary for the website, as the website is only showing a summary, I don't think people will do verifications of data directly from the website. 

Spitting into two is the best option then I guess. 10 per-page limit is fine as is.
